server:
  port: 8080

spring:
  application:
    name: core-banking-system
  datasource:
    url: jdbc:postgresql://localhost:5432/cbs
    username: cbs
    password: cbs
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

security:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 3600000
    refresh-token:
      expiration: 86400000
